WIP: unhardcode CompositionProvider (fix #79)
Starcounter/starcounter-include pull request #80
Opened 2018-01-03 12:57 UTC by tomalec

It could be configured per instance as well as globally by updating the prototype.

remaining: update tests, add new one

Related issues:
https://github.com/Starcounter/starcounter-include/issues/30
https://github.com/Starcounter/starcounter-include/issues/43
https://github.com/Starcounter/starcounter-include/issues/79

2018-01-03 13:59 UTC, warpech commented
The only way of providing a new value for the namespace name that we have right now, requires overwriting `/sys/starcounter.html` through middleware in BlendingProvider. 

It was identified as an antipattern in https://github.com/Starcounter/CompositionEditor/issues/8 and we want to stop using it.

Do you have some ideas for a better pattern or will we have to use the antipattern for now?

2018-01-03 14:00 UTC, warpech requested changes
It will be tough change because it moves the shitty responsibility to determine the namespace to an even more obscure place. But I agree it will make the codebase cleaner.

2018-01-03 14:00 UTC, warpech commented on README.md
> +`CompositionProvider` | *String* | `CompositionProvider_0` | Key/app name of composition provider. could be overwritten per instance `scInclude.CompositionProvider` or globally by changing the protot
I think this property name should be lowercase, as all other property names.

2018-01-03 17:24 UTC, tomalec commented
I would say doing single line 
```js
customElements.get('starcounter-include').prototype.compositionProvider
```
 anywhere in your code is waay less obscure, than 

0. Stop all your apps,
1. Fork `sc-include`,
2. Change hardcoded value,
3. Fork level1,
4. Install forked `sc-include`,
5. Build level1,
6. Start all your apps,
7. Repeat = maintain :finnadie:

2018-01-03 17:27 UTC, tomalec commented
> Do you have some ideas for a better pattern or will we have to use the antipattern for now?

Stop pretending we do not have starcounter-specific node in the view-model tree and provide such metadata in view model https://github.com/Starcounter/RebelsLounge/issues/97 possibly in the same convention as Palindrom  metadata

2018-01-03 17:43 UTC, warpech commented
> Stop pretending we do not have starcounter-specific node in the view-model tree and provide such metadata in view model Starcounter/RebelsLounge#97 possibly in the same convention as Palindrom metadata

Same thing came to my mind today. We should get back to this. For now, this solution is OK, just please make the property name lowercase.

2018-01-04 10:20 UTC, tomalec commented
@warpech  Please check now.

2018-01-04 10:54 UTC, warpech approved these changes
Lgtm

2018-01-04 11:23 UTC, merged

2018-01-04 11:39 UTC, tomalec commented
Released in https://github.com/Starcounter/starcounter-include/releases/tag/4.2.0

2018-01-04 20:11 UTC, tomalec commented
Tests could be added as part of https://github.com/Starcounter/starcounter-include/issues/43