Deprecate partial attribute
Starcounter/starcounter-include pull request #94
Opened 2018-03-01 11:56 UTC by alshakero

Changed all `partial` property and attribute usages in tests in favor of `view-model` and viewModel. And added tests for the warnings.

2018-03-01 12:05 UTC, tomalec commented on starcounter-include.html
> +            console.warn('`partial` attribute and property are deprecatrd from `starcounter-include` in fovour of (viewModel property or view-model attribute), they will soon be no longer be supporte
"deprecatrd" -> "deprecated"

2018-03-01 12:10 UTC, tomalec requested changes

2018-03-01 12:10 UTC, tomalec commented on starcounter-include.html
>                  var partial = this.viewModel || this.partial || undefined;
I think we should use `viewModel` instead of `partial` internally as wel..

2018-03-01 12:10 UTC, tomalec commented on starcounter-include.html
> +                            this.settingPartialFromModel = true;
If we will use `viewModel` internall (which we should in my opinion), that kind of magic will not be needed. Unless you do this just to reflect the old `partial` values set to `viewModel`

2018-03-01 12:10 UTC, tomalec commented on starcounter-include.html
> +                this.partial = partialAttributeToProperty(this, newVal);
We should use `.viewModel` internally

2018-03-01 13:03 UTC, alshakero commented
Done.

2018-03-01 17:32 UTC, tomalec requested changes

2018-03-01 17:32 UTC, tomalec commented on .vs/ProjectSettings.json
> +{
Please add those files to gitignore

2018-03-05 11:41 UTC, warpech approved these changes
Lgtm

2018-03-05 11:44 UTC, warpech commented
I was asked to merge by @alshakero, even though the status of @tomalec review is still red. We believe @tomalec would change to green now, but he can't since he is in Tokio now.

 Merging.

2018-03-05 11:45 UTC, merged