Cache <style> tags for better perf and fix FOUC
Starcounter/starcounter-include pull request #97
Opened 2018-03-12 11:06 UTC by alshakero

My gut feeling is that it's a tad intrusive. But I don't have a solid argument against it. It makes more sense to me than issuing a network request for same `uniform.css` file with every navigation.

2018-03-12 11:22 UTC, alshakero commented
The failure on Safari isn't related to my change and I'm working on fixing it. So feel free to review.

2018-03-15 15:00 UTC, alshakero commented
@warpech I managed to fix Edge issue in Uniform. This fixes it too.

2018-03-20 09:35 UTC, warpech commented
Normally caching of the stylesheet should be solved by `link rel="preload"`, by that works only in Chrome. 

Maybe it is actually smart to polyfill `link rel="preload"`, but I think that @tomalec will really dislike replacing `<link href="">` with an inlined `<style>`. Maybe for non-Chrome browsers we could actually accept that?

Let's put this review on pause until @tomalec is back from vacation. This PR is one of three proposed solutions for #93.

2018-03-21 13:03 UTC, tomalec requested changes

2018-03-21 13:03 UTC, tomalec commented on starcounter-include.html
> +                                    const style = await fetchStyle(link.href);
Isn't it making a cascade of fetches? One requests wait for another instead of bulking them.

2018-03-21 13:03 UTC, tomalec commented on starcounter-include.html
> +        fetchStyle(new URL('/sys/uniform.css/uniform.css', window.location).href);
I think `stracounter-include` should not impose `'/sys/uniform.css/uniform.css'` being loaded. It's
- hidden dependency on uniform.css,
- hidden requirement to keep it in that exact path,

I don't see a reason to force Starcounter include users to use uniform.

2018-03-21 13:04 UTC, tomalec commented
I think it may become a non-GC-able, black hole, as user agent navigates through many nested partials.

We should at least remove styles from the Map when the partial view containing the resource is removed/changed. However, it still won't cover resources requested or removed asynchronously.

I got the feeling that this is an attempt to do browser's job and reinvent the wheel. I'd rather go this part once all the other ideas fail.

2018-08-07 14:24 UTC, alshakero commented
Closing as it's a bad idea.

2018-08-07 14:24 UTC, closed without merging